// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	LoginRequest
	LoginResponse
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import mzmico_protobuf "github.com/mzmico/protobuf"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Session     *mzmico_protobuf.Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Account     string                   `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	Certificate string                   `protobuf:"bytes,3,opt,name=certificate" json:"certificate,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginRequest) GetSession() *mzmico_protobuf.Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *LoginRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginRequest) GetCertificate() string {
	if m != nil {
		return m.Certificate
	}
	return ""
}

type LoginResponse struct {
	Uid   string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "service.user.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "service.user.LoginResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for User service

type UserClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/service.user.user/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.user.user/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.user.user",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _User_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x25, 0x94, 0x52, 0xf5, 0x5a, 0x24, 0x64, 0x31, 0x58, 0x41, 0x48, 0x51, 0x16, 0xca, 0x80,
	0x23, 0x85, 0x81, 0xbd, 0x23, 0x62, 0x0a, 0x1b, 0x5b, 0x63, 0xae, 0xc5, 0x42, 0xf1, 0x95, 0x9c,
	0xcd, 0xc0, 0xc0, 0xb7, 0xa3, 0xd8, 0x0e, 0xca, 0xc0, 0x76, 0x77, 0xef, 0xdd, 0x7b, 0x7a, 0x0f,
	0xc0, 0x33, 0xf6, 0xea, 0xd8, 0x93, 0x23, 0xb1, 0x66, 0xec, 0xbf, 0x8c, 0x46, 0x35, 0xdc, 0xf2,
	0x9b, 0xee, 0xbb, 0x33, 0x9a, 0xaa, 0x80, 0xb5, 0x7e, 0x5f, 0x31, 0x32, 0x1b, 0xb2, 0x91, 0x5c,
	0xfe, 0xc0, 0xfa, 0x99, 0x0e, 0xc6, 0x36, 0xf8, 0xe9, 0x91, 0x9d, 0xa8, 0x61, 0x91, 0x08, 0x32,
	0x2b, 0xb2, 0xcd, 0xaa, 0x96, 0x2a, 0x0a, 0xa8, 0x51, 0x40, 0xbd, 0x44, 0xbc, 0x19, 0x89, 0x42,
	0xc2, 0x62, 0xa7, 0x35, 0x79, 0xeb, 0xe4, 0x69, 0x91, 0x6d, 0x96, 0xcd, 0xb8, 0x8a, 0x02, 0x56,
	0x1a, 0x7b, 0x67, 0xf6, 0x46, 0xef, 0x1c, 0xca, 0x59, 0x40, 0xa7, 0xa7, 0xf2, 0x11, 0x2e, 0x92,
	0x3f, 0x1f, 0xc9, 0x32, 0x8a, 0x4b, 0x98, 0x79, 0xf3, 0x16, 0xcc, 0x97, 0xcd, 0x30, 0x8a, 0x2b,
	0x98, 0x3b, 0xfa, 0x40, 0x9b, 0xc4, 0xe3, 0x52, 0x3f, 0xc1, 0xd9, 0x90, 0x4f, 0x6c, 0x61, 0x1e,
	0x04, 0x44, 0xae, 0xa6, 0xb9, 0xd5, 0x34, 0x55, 0x7e, 0xfd, 0x2f, 0x16, 0x1d, 0xcb, 0x93, 0xed,
	0xdd, 0xeb, 0xed, 0xc1, 0xb8, 0x77, 0xdf, 0x2a, 0x4d, 0x5d, 0x95, 0x0a, 0x1b, 0x98, 0xf7, 0xe9,
	0xed, 0xaf, 0xbd, 0xf6, 0x3c, 0x4c, 0x0f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xca, 0x3a, 0xff,
	0xb9, 0x71, 0x01, 0x00, 0x00,
}
